### PR TITLE
Refactor script

### PR DESCRIPTION
**Pull request by zmughal**
Refactors the original `curie.pl` script into modules.

### CODE REVIEW

**Comment by StayerX** [comment]
I like the new structure, it is cleaner. If you approve I am good for the commit.

**Comment by zmughal** [comment]
It's not done yet. I'll ping again when it is ready.

**Comment by zmughal** [comment]
@project-renard/dev, the refactored code is ready. Please review.

**Comment by ChiragGhanshani** [comment]
Looks good to me. I'll fix bug #1 while I work on the buttons later tonight.

**Comment by zmughal** [comment]
Do you mean bug #21?

**Comment by ChiragGhanshani** [comment]
I mean the first bug on the list that Stan posted above.

**Comment by zmughal** [comment]
Ah, so bug #22.

**Pull request merged**
