### PR TITLE
Open files through drag-and-drop

### LINKED ISSUE #19: Drag and drop for opening files
- https://developer.gnome.org/gtk3/stable/gtk3-Drag-and-Drop.html
- http://python-gtk-3-tutorial.readthedocs.io/en/latest/drag_and_drop.html
- http://www.openshotvideo.com/2008/09/drag-drop-with-gtk-and-python.html
- http://stackoverflow.com/questions/14273471/drag-and-drop-files-into-program

### PR DESCRIPTION
**Pull request by zmughal**
Goal:

- When a file is dragged on to the page drawing area, it gets opened.

Fixes #19.

### CODE REVIEW

**Comment by zmughal** [comment]
@StayerX could you continue this PR?

**Comment by zmughal** [comment]
The build is broken until <https://github.com/project-renard/curie/pull/173> is merged. You can still continue working on this branch of course, but you might want to rebase off master after it is merged.

**Comment by zmughal** [comment]
I went ahead and did the rebase off master myself. #173 has been merged in to that.

**Comment by zmughal** [comment]
@StayerX, have you had a chance to look at this?

**Comment by zmughal** [comment]
@StayerX , I have rebased this off master. It should be up to date.

Try running this branch and drag a file on to the application. Take note of what is printed out in the console.

**Comment by zmughal** [comment]
@StayerX , after doing some reading through different documentation and examples, this is what I have realised: we can not emulate drag-and-drop programmatically in the tests. The reason is because the Gtk3::SelectionData is an opaque struct. Usually these opaque structs are able to constructed because there is something called a glib boxed type that [defines how to create and destroy them](https://developer.gnome.org/gobject/unstable/gobject-Type-Information.html#G-DEFINE-BOXED-TYPE:CAPS). Because [GtkSelectionData](https://developer.gnome.org/gtk3/stable/gtk3-Selections.html#GtkSelectionData-struct) does not have a comment that defines the contents of the struct, it is not available to be constructed via the binding:
```perl
0:main
$ Glib::Boxed::new('Gtk3::SelectionData')
Runtime error: Cannot create boxed struct of unknown size for package Gtk3::SelectionData at (eval 424) line 5.
```

So instead, we can create a MockObject and pass it directly to the callback. Here's something to get you started:

```perl
my $pdf_ref_path = try {
	CurieTestHelper->test_data_directory->child(qw(PDF Adobe pdf_reference_1-7.pdf));
} catch {
	plan skip_all => "$_";
};
my $pdf_ref_uri = URI::file->new($pdf_ref_path);

my $app = Renard::Curie::App->new;

my $data = Test::MockObject->new( );
$data->mock( get_uris => sub { [ "$pdf_ref_uri" ] } );

my @signal_args = (
	undef, # $context
	0,     # $x
	0,     # $y
	$data, # $data
	Renard::Curie::App::DND_TARGET_URI_LIST, # $info
	0, # $time
	$app, # $app
);
```

then take those args and call the callback function directly:

```perl
Renard::Curie::App::on_drag_data_received_cb( $app->content_box, @signal_args )
```

Then check that the filename opened is correct.

**Comment by zmughal** [comment]
Another note: we can't use `signal_emit` to do the work with the MockObject because it really is not a `Gtk3::SelectionData` object that the callback expects. The glib type system catches that.

**Comment by zmughal** [comment]
@StayerX, will this be ready by the meeting on Saturday?

**Comment by StayerX** [comment]
@zmughal it is done but only thanks to you!

**Comment by zmughal** [comment]
I will merge and release v0.002 tonight!

**Pull request merged**
