### PR TITLE
Reduced the height of the status bar.

### LINKED ISSUE #40: The status bar is too wide
- [ ] 1. We should reduce the thickness of the bar
- [ ] 2. Discuss possible functionalities such as page info, zoom level, zoom button (see review of pdf viewers as a starting point [link-should-be-added-here])

glade-status-bar

### PR DESCRIPTION
**Pull request by StayerX**
Fixes #40.

@project-renard/dev I think this is  ready for your review.

### CODE REVIEW

**Comment by StayerX** [comment]
It is able to increase the size but cannot reduce it lower that a threshold .
I think they have done something of the sort: height = max(minimum_height, height)

**Comment by zmughal** [comment]
@StayerX, maybe it might be worth switching to GtkGrid? This seems to give a lot of information about how it works https://developer.gnome.org/gtk3/stable/gtk-migrating-GtkGrid.html.

**Comment by zmughal** [comment]
I'll try to rebase this later today and make a test to check the size.

**Comment by zmughal** [comment]
We'll just get rid of the status bar. Closing.

**Pull request closed without merging**
