### PR TITLE
Add a `cpanfile` that contains the basic Perl dependencies

### PR DESCRIPTION
**Pull request by zmughal**
This will make it easier to install automatically with the command:

``` shell
  cpanm --installdeps .
```

> Meeting log: https://project-renard.github.io/doc/development/meeting-log/posts/2016/01/24/initial-setup/

### CODE REVIEW

**Comment by zmughal** [comment]
@project-renard/dev, Does this look good to merge?

**Comment by ChiragGhanshani** [comment]
Looks good to me.

**Comment by StayerX** [comment]
Me too.

**Comment by zmughal** [comment]
Meeting log <https://project-renard.github.io/doc/development/meeting-log/posts/2016/01/24/initial-setup/>

**Pull request merged**
