### PR TITLE
Start adding unit tests

### PR DESCRIPTION
**Pull request by zmughal**
This addresses issue #28.

### CODE REVIEW

**Comment by zmughal** [comment]
To run the tests, you need to set an environment variable to point the [test-data](http://github.com/project-renard/test-data) repository

``` shell
 RENARD_TEST_DATA_PATH=~/sw_projects/project-renard/test-data/test-data prove -lrv xt/
```

**Comment by zmughal** [comment]
Don't merge this yet!

**Comment by ChiragGhanshani** [comment]
There are two errors, so I was about to say no.

**Comment by zmughal** [comment]
@project-renard/dev, please review the code now for merging. I plan on writing more tests for the GUI itself in another pull request.

**Comment by StayerX** [comment]
Since the only new thing since my initial approval is Travis and it passed I agree with the pull request.
@ChiragGhanshani what do you say?

**Comment by ChiragGhanshani** [comment]
Tests are passing!! Looks good to me!!

**Comment by zmughal** [comment]
I think you closed it without merging :-P

**Pull request merged**
