### PR TITLE
Scrolling drawing area

### PR DESCRIPTION
**Pull request by zmughal**

### CODE REVIEW

**Comment by StayerX** [comment]
My stupid "tiny" comment is still there :P. I know I added lines 240 to 243, but do we need them? What is your opinion.Apart from that it looks OK. The appropriate PDF page size is still an issue.

Do you believe it can automatically detect that or do we need to find it in the PDF meta info and set it up?

**Comment by StayerX** [comment]
Other than that I am approving.

**Comment by ChiragGhanshani** [comment]
I can't scroll. I'm on the simple-gui-scrollable branch so I should be able to.

**Comment by StayerX** [comment]
Try to reduce the size of the window. It will appear then. The next step will be to make it aware of its dimensions.

**Comment by zmughal** [comment]
@project-renard/dev, hey, can you all review the changes so far?

**Comment by zmughal** [comment]
Demonstrates the scrollbar:

curie-scroll-drawing-area

**Comment by StayerX** [comment]
Great, lets merge

**Pull request merged**
